### ISSUE TITLE
pip install pytiff fails when numpy is not available

### ISSUE THREAD

**Issue by ylep** [FZJ-INM1-BDA/pytiff#6]
pip install pytiff     
Downloading/unpacking pytiff
  Downloading pytiff-0.7.0.tar.gz (1.3MB): 1.3MB downloaded
  Running setup.py (path:/tmp/pip-build-3abmxk7b/pytiff/setup.py) egg_info for package pytiff
    Traceback (most recent call last):
      File "/tmp/pip-build-3abmxk7b/pytiff/setup.py", line 13, in <module>
        import numpy
    ImportError: No module named 'numpy'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-3abmxk7b/pytiff/setup.py", line 15, in <module>
        raise Exception("Numpy is needed for installation")
    Exception: Numpy is needed for installation
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "/tmp/pip-build-3abmxk7b/pytiff/setup.py", line 13, in <module>

    import numpy

ImportError: No module named 'numpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-3abmxk7b/pytiff/setup.py", line 15, in <module>

    raise Exception("Numpy is needed for installation")

Exception: Numpy is needed for installation

**Comment by pglock** [comment]
This is working as intended. Pytiff needs the numpy header files, so it must be already installed
